### PR TITLE
[Torch] Add 1.6.0 and 1.7.0 to CI

### PR DESCRIPTION
**Pull request by VivekPanyam**
### Summary:
No major code changes were required to add support for Torch 1.6.0 or Torch 1.7.0. This PR adds both of these builds to CI.

A future PR will likely remove the Torch 1.1.0 build from CI in order to limit the resources we use on every PR.

### Test Plan:
- CI 
- Internal testing at ATG (where we've used Torch 1.6.0 with Neuropod for a while)

### CODE REVIEW

**Comment by davidxiaozhi** [comment]
@VivekPanyam  Hello, I plan to use neuroPod in the next project, but the deep learning frameworks used by the team are basically the latest versions of TensorFlow (2.3) and pytorch (1.7). What is the current progress of this adaptation? Time can be used in production environment

**Review by sepo-eng — APPROVED** [review]
LGTM, given the SHA is added for 1.7.0

**Comment by VivekPanyam** [comment]
> @VivekPanyam Hello, I plan to use neuroPod in the next project, but the deep learning frameworks used by the team are basically the latest versions of TensorFlow (2.3) and pytorch (1.7). What is the current progress of this adaptation? Time can be used in production environment

@davidxiaozhi We're working on TF 2.3 support, but there are some issues there (see https://github.com/uber/neuropod/pull/455#issuecomment-731973576). The next release of Neuropod should have support for (at least) TF 2.2 and Torch 1.7.

We've had various teams internally using TF 2.x and Torch >= 1.6 with Neuropod for a while. We haven't released prebuilt binaries for these frameworks, but a new Neuropod release containing these should be coming soon.

**Comment by davidxiaozhi** [comment]
@VivekPanyam   I am looking forward to the release of the new release version. In addition, does our neuroPod have some  demo  for   inference  which project build by c++ ? I see that our documentation is not very detailed

**Comment by davidxiaozhi** [comment]
@VivekPanyam 
The GitHub branch has been merged, but the version of torchscript in backend_registration.cc is supported, and the two versions 1.6.0 and 1.7.0 have not been added

`  const std::vector<FrameworkInfo> frameworks = {
        {"torchscript", "libneuropod_torchscript_backend.so", true, {"1.1.0", "1.2.0", "1.3.0", "1.4.0", "1.5.0"}},
        {"tensorflow", "libneuropod_tensorflow_backend.so", true, {"1.12.0", "1.13.1", "1.14.0", "1.15.0", "2.2.0"}},
        {"python", "libneuropod_pythonbridge_backend.so", false, {"2.7", "3.5", "3.6", "3.7", "3.8"}}};`

**Comment by VivekPanyam** [comment]
@davidxiaozhi Sorry I missed your comment from a few weeks ago!

> @VivekPanyam I am looking forward to the release of the new release version. In addition, does our neuroPod have some demo for inference which project build by c++ ? I see that our documentation is not very detailed

The docs at https://neuropod.ai/docs/stable/installing/ talk through installing Neuropod (for both C++ and Python).
The docs at https://neuropod.ai/docs/stable/developing/ show how to build Neuropod from source.

Once you have Neuropod installed, you can use it by following the basic introduction tutorial here: https://neuropod.ai/docs/stable/tutorial/

Near the bottom of that page, there's an example of loading a model from C++ and running inference.

You can also see the C++ guide (https://neuropod.ai/docs/stable/cppguide/) or our tests for more details. [This](https://github.com/uber/neuropod/blob/master/source/neuropod/tests/test_utils.hh) utility from our tests might be useful to look at.

> @VivekPanyam 
The GitHub branch has been merged, but the version of torchscript in backend_registration.cc is supported, and the two versions 1.6.0 and 1.7.0 have not been added
> 
> `  const std::vector<FrameworkInfo> frameworks = {
        {"torchscript", "libneuropod_torchscript_backend.so", true, {"1.1.0", "1.2.0", "1.3.0", "1.4.0", "1.5.0"}},
        {"tensorflow", "libneuropod_tensorflow_backend.so", true, {"1.12.0", "1.13.1", "1.14.0", "1.15.0", "2.2.0"}},
        {"python", "libneuropod_pythonbridge_backend.so", false, {"2.7", "3.5", "3.6", "3.7", "3.8"}}};`


The code you're referring to is out of date. If you look at the [changes](https://github.com/uber/neuropod/pull/456/files#diff-f17061709a4323fc08c49128593ba2dba6f1f652cb98841b00f7c4a018ac3e29) that were made to `backend_registration.cc` in this PR (the one we're currently commenting on), you'll see that we add support for 1.6.0 and 1.7.0.

Release candidates for the next version of Neuropod (along with new installation docs) should be coming this week.

**Pull request merged**
